defaults:
  - _self_
  - planner: gd
env: point_maze
hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_${model_name}_gH${goal_H}

# model to load for planning
ckpt_base_path: ${oc.env:TCWM_DATA_ROOT,./data}/checkpoints  # set to your trained run dir
model_name: null
model_epoch: latest

seed: 99
n_evals: 10
goal_source: 'dset' # 'random_state' or 'dset' or 'random_action' 
goal_H: 5 # specifies how far away the goal is if goal_source is 'dset'
n_plot_samples: 10

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2 # coeff base for weighting all frames. Only applies when mode == 'all'
  mode: last

wandb:
  project: tasuw
  name: "linear_projector_history_196_64"
  entity: null
